export enum MainFeeling {
  ANGRY = 'angry',
  HAPPY = 'happy',
  STRONG = 'strong',
  SAD = 'sad',
  SAFE = 'safe',
  SCARED = 'scared',
}

// TODO: TRANSLATIONS HERE

export const FEELINGS = {
  [MainFeeling.ANGRY]: {
    BETRAYED: 'betrayed',
    BITTER: 'bitter',
    CRITICAL: 'critical',
    DEVASTATED: 'devastated',
    DISGUSTED: 'disgusted',
    FRUSTRATED: 'frustrated',
    ANGRY: 'angry',
    DETESTABLE: 'detestable',
    HOSTILE: 'hostile',
    HURT: 'hurt',
    IRRITATED: 'irritated',
    INDIGNANT: 'indignant',
  },
  [MainFeeling.HAPPY]: {
    ENERGETIC: 'energetic',
    CHEERFUL: 'cheerful',
    CREATIVE: 'creative',
    CURIOUS: 'curious',
    DARING: 'daring',
    HOPEFUL: 'hopeful',
    FULL_OF_IMAGINATION: 'full_of_imagination',
    LIGHT: 'light',
    OPTIMISTIC: 'optimistic',
    PLAYFUL: 'playful',
    // TODO: not sure about this one ('simtit' in romana)
    THIN_SKINNED: 'thin_skinned',
    PROVOCATIVE: 'provocative',
  },
  [MainFeeling.STRONG]: {
    APPRECIATED: 'appreciated',
    CONFIDENT: 'confident',
    DISCERNING: 'discerning',
    ENERGETIC: 'energetic',
    NOURISHING: 'nourishing',
    PROUD: 'proud',
    RESPECTED: 'respected',
    RECEPTIVE: 'receptive',
    SUCCESSFUL: 'successful',
    GRATEFUL: 'grateful',
    CHERISHED: 'cherished',
    VALUABLE: 'valuable',
  },
  [MainFeeling.SAD]: {
    EMBARRASSED: 'embarrassed',
    BORED: 'bored',
    COLD: 'cold',
    DEPRESSED: 'depressed',
    DESPERATE: 'desperate',
    DISCONNECTED: 'disconnected',
    EMPTY: 'empty',
    HOPELESS: 'hopeless',
    HUMILIATED: 'humiliated',
    LONELY: 'lonely',
    TIRED: 'tired',
    WORTHLESS: 'worthless',
  },
  [MainFeeling.SAFE]: {
    ACCEPTED: 'accepted',
    CALM: 'calm',
    LOVED: 'loved',
    OPEN: 'open',
    PEACEFUL: 'peaceful',
    PROTECTED: 'protected',
    SILENT: 'silent',
    RELAXED: 'relaxed',
    CARING: 'caring',
    UNDERSTOOD: 'understood',
    WARM: 'warm',
  },
  [MainFeeling.SCARED]: {
    ABANDONED: 'abandoned',
    ANXIOUS: 'anxious',
    PERPLEXED: 'perplexed',
    HELPLESS: 'helpless',
    INADEQUATE: 'inadequate',
    INSIGNIFICANT: 'insignificant',
    NUMB: 'numb',
    OVERWHELMED: 'overwhelmed',
    PARALYZED: 'paralyzed',
    SHOCKED: 'shocked',
    BLOCKED: 'blocked',
    VULNERABLE: 'vulnerable',
  },
} as const;
